package HeightConverter.UI;

import HeightConverter.Calculating;
import HeightConverter.Strings;

import javax.swing.*;
import java.awt.*;

public class GUI {
    private JPanel panel1;
    private JTextField feetTextField;
    private JTextField inchesTextField;
    private JButton convertButton;
    private JButton exitButton;
    private JButton clearButton;
    private JTextField cmTextField;
    private JLabel feetLabel;
    private JLabel inchesLabel;
    private JLabel cmLabel;

    public void setButtonsListeners() {
        setExitButtonListener();
        setClearButtonListener();
        setConvertButtonListeners();
    }
    private void setConvertButtonListeners() {
        convertButton.addActionListener(e -> Calculating.calculate(this));
    }
    private void setClearButtonListener() {
        clearButton.addActionListener(e -> clearAction());
    }
    private void clearAction() {
        feetTF_clear();
        inchesTF_clear();
        cmTF_clear();
    }
    public void cmTF_clear() {
        cmTextField.setText(Strings.clearString);
    }
    public void inchesTF_clear() {
        inchesTextField.setText(Strings.clearString);
    }
    public void feetTF_clear() {
        feetTextField.setText(Strings.clearString);
    }
    private void setExitButtonListener() {
        exitButton.addActionListener(e -> System.exit(0));
    }
    public void setTexts() {
        feetLabel.setText(Strings.feetLabelText);
        inchesLabel.setText(Strings.inchesLabelText);
        cmLabel.setText(Strings.cmLabelText);
        convertButton.setText(Strings.convertButtonText);
        clearButton.setText(Strings.clearButtonText);
        exitButton.setText(Strings.exitButtonText);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(400, 300));
        feetLabel = new JLabel();
        feetLabel.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(feetLabel, gbc);
        feetTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(feetTextField, gbc);
        inchesLabel = new JLabel();
        inchesLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(inchesLabel, gbc);
        inchesTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(inchesTextField, gbc);
        convertButton = new JButton();
        convertButton.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(convertButton, gbc);
        exitButton = new JButton();
        exitButton.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(exitButton, gbc);
        clearButton = new JButton();
        clearButton.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(clearButton, gbc);
        cmLabel = new JLabel();
        cmLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(cmLabel, gbc);
        cmTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(cmTextField, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 20;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 20;
        panel1.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public JPanel getPanel1() {
        return panel1;
    }
    public JTextField getFeetTextField() {
        return feetTextField;
    }
    public JTextField getInchesTextField() {
        return inchesTextField;
    }
    public JButton getConvertButton() {
        return convertButton;
    }
    public JButton getExitButton() {
        return exitButton;
    }
    public JButton getClearButton() {
        return clearButton;
    }
    public JTextField getCmTextField() {
        return cmTextField;
    }
    public JLabel getFeetLabel() {
        return feetLabel;
    }
    public JLabel getInchesLabel() {
        return inchesLabel;
    }
    public JLabel getCmLabel() {
        return cmLabel;
    }
}
